### PR TITLE
feat: add "create component" snippet

### PR DESCRIPTION
**Pull request by doong-jo**
1. Create component
ecp

2. Create component (Typescript interface)
etcp

### CODE REVIEW

**Review by mskelton — COMMENTED** [review]
Love the idea for this snippet.  A few initial questions come to mind:

1. I think it might make more sense to have the keyword be `cec` for "create Emotion component".  Thoughts?
2. Rather than having a separate snippet for TypeScript, why don't we just use a single snippet prefix and contribute different files for JS/TS.  This would look something like this in package.json

```json
{
        "language": "javascript",
        "path": "./snippets/js.json"
      },
      {
        "language": "javascriptreact",
        "path": "./snippets/js.json"
      },
      {
        "language": "typescriptreact",
        "path": "./snippets/tsx.json"
      },
```

3. `export default` worries me a bit.  Some developers prefer export default, others (like me) prefer named exports.  We could provide two different snippets, though I'm not sure if I really like that idea.  One thing we could do instead (which would probably be outside the scope of this PR would be to add settings which would adjust what the snippets output.  I have an example of this in my VS Code color theme here: https://github.com/one-dark/vscode-one-dark-theme/blob/master/src/extension.ts

**Comment by doong-jo** [comment]
1, 2. yes, it was good. (I'm still not sure about the preferences for snippets. now, I knew)

3. As you said, I think this part is different for each developer. How about providing it with the exception of the "export" part and leaving the rest to the developer?

**Comment by mskelton** [comment]
Thanks again for contributing!

**Comment by mskelton** [comment]
@all-contributors add @doong-jo to code

**Pull request merged**
